[versions]

kotlin = "1.5.0"

[libraries]

android-gradlePlugin = "com.android.tools.build:gradle:7.0.0-alpha15"

androidx-compose-runtime = "androidx.compose.runtime:runtime:1.0.0-beta05"

autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.0" }
autoService-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "0.5.0" }

dokka-gradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.4.32" }

junit = { module = "junit:junit", version = "4.13.2" }

kotlin-compileTesting = { module = "com.github.tschuchortdev:kotlin-compile-testing", version = "1.4.0" }
kotlin-embeddableCompiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePluginApi = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }

kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version = "0.5.0" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.3.6" }

ksp-gradlePlugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version = "1.5.0-1.0.0-alpha09" }

truth = { module = "com.google.truth:truth", version = "1.1.2" }
